version: 0.0
os: linux
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: bin/pre_install.sh
  AfterInstall:
    - location: bin/post_install.sh
      timeout: 300
#  ApplicationStart:
#    - location: Scripts/RunFunctionalTests.sh
#      timeout: 3600
#  ValidateService:
#    - location: Scripts/MonitorService.sh
#      timeout: 3600
#      runas: codedeployuser